Pet.create!([
  {name: "Soba", gender: "Male", breed: "Domestic Short Hair", bio: "Loves to knead and drool", species: "Cat", search_terms: "Soba Male Domestic Short Hair Cat", user_id: 1},
  {name: "Russell", gender: "Male", breed: "Toy Poodle Mix", bio: "", species: "Dog", search_terms: "Russell Male Toy Poodle Mix Dog", user_id: 1},
  {name: "Dane", gender: "", breed: "", bio: "", species: "", search_terms: "Dane   ", user_id: 1},
  {name: "Cole", gender: "Male", breed: "Turkish Angora", bio: "Trying to break the stereotype of black cats being unlucky and therefore undeserving of love", species: "Cat", search_terms: "Cole Male Turkish Angora Cat", user_id: 1},
  {name: "Marmalade", gender: "Male", breed: "Ginger Tabby", bio: "Ready to take on the world!", species: "Cat", search_terms: "Marmalade Male Ginger Tabby Cat", user_id: 1},
  {name: "Agee", gender: "Female", breed: "Polar Bear", bio: "", species: "Bear", search_terms: "Agee Female Polar Bear Bear", user_id: 1},
  {name: "Ben", gender: "", breed: "Trash Panda", bio: "", species: "Raccoon", search_terms: "Ben  Trash Panda Raccoon", user_id: 1},
  {name: "Ramen", gender: "Male", breed: "German Shepherd", bio: "", species: "Dog", search_terms: "Ramen Male German Shepard Dog", user_id: 1},
  {name: "Meatloaf", gender: "Female", breed: "Chihuahua", bio: "", species: "Dog", search_terms: "Meatloaf Female Chihuahua Dog", user_id: 1},
  {name: "Honey", gender: "Female", breed: "Short Hair", bio: "", species: "Hamster", search_terms: "Honey Female Short Hair Hamster", user_id: 1},
  {name: "Nylah", gender: "Female", breed: "Bengal Cat", bio: "", species: "Cat", search_terms: "Nylah Female Bengal Cat Cat", user_id: 1},
  {name: "Bambu", gender: "Male", breed: "Bengal Cat", bio: "", species: "Cat", search_terms: "Bambu Male Bengal Cat Cat", user_id: 1},
  {name: "Memphis", gender: "Female", breed: "Siberian Husky", bio: "A puppy with unlimited energy.", species: "Dog", search_terms: "Memphis Female Siberian Husky Dog", user_id: 1},
  {name: "Shelby", gender: "Female", breed: "Siberian Husky", bio: "A diva", species: "Dog", search_terms: "Shelby Female Siberian Husky Dog", user_id: 1},
  {name: "Oakley", gender: "Female", breed: "Siberian Husky", bio: "The gentle giant.", species: "Dog", search_terms: "Oakley Female Siberian Husky Dog", user_id: 1},
  {name: "Harley", gender: "", breed: "", bio: "", species: "Dog", search_terms: "Harley   ", user_id: 1},
  {name: "Pebble", gender: "", breed: "Tibetan Mastiff", bio: "", species: "Dog", search_terms: "Pebble  Tibetan Mastiff Dog", user_id: 1},
  {name: "Bernie", gender: "", breed: "Bernese Mountain Dog", bio: "", species: "Dog", search_terms: "Bernie   Dog", user_id: 1},
  {name: "Randy", gender: "", breed: "", bio: "", species: "Dog", search_terms: "Randy   Dog", user_id: 1},
  {name: "Furball", gender: "", breed: "", bio: "", species: "Cat", search_terms: "Furball   Cat", user_id: 1},
  {name: "General Kitty", gender: "", breed: "", bio: "", species: "Cat", search_terms: "General Kitty   Cat", user_id: 1},
  {name: "Fat Cat", gender: "", breed: "", bio: "", species: "Cat", search_terms: nil, user_id: 1},
  {name: "Corbin", gender: "Male", breed: "", bio: "", species: "Human", search_terms: nil, user_id: 1},
  {name: "Finn", gender: "", breed: "", bio: "", species: "Cat", search_terms: nil, user_id: 1},
  {name: "", gender: "", breed: "Andean Mountain Cat", bio: "", species: "", search_terms: nil, user_id: 1},
  {name: "", gender: "", breed: "Pallas Cat", bio: "", species: "", search_terms: nil, user_id: 1},
  {name: "", gender: "", breed: "Fishing Cat", bio: "", species: "", search_terms: nil, user_id: 1},
  {name: "", gender: "", breed: "Sand Cat", bio: "", species: "", search_terms: nil, user_id: 1},
  {name: "", gender: "", breed: "Margay", bio: "", species: "", search_terms: nil, user_id: 1},
  {name: "", gender: "", breed: "Black-footed Cat", bio: "", species: "", search_terms: nil, user_id: 1},
  {name: "", gender: "", breed: "Chinese Mountain Cat", bio: "", species: "", search_terms: nil, user_id: 1},
  {name: "", gender: "", breed: "African Golden Cat", bio: "", species: "", search_terms: nil, user_id: 1},
  {name: "", gender: "", breed: "Caracal", bio: "", species: "", search_terms: nil, user_id: 1},
  {name: "", gender: "", breed: "Flat-Headed Cat", bio: "", species: "", search_terms: nil, user_id: 1},
  {name: "", gender: "", breed: "Kodkod", bio: "", species: "Cat", search_terms: nil, user_id: 1},
  {name: "Curiosity", gender: "", breed: "", bio: "", species: "Cat", search_terms: nil, user_id: 1},
  {name: "", gender: "", breed: "Puppy", bio: "", species: "", search_terms: nil, user_id: 1},
  {name: "", gender: "", breed: "", bio: "", species: "dog", search_terms: nil, user_id: 1},
  {name: "", gender: "", breed: "Programmer", bio: "", species: "", search_terms: nil, user_id: 1}
])

Album.create!([
  {title: "Profile", description: "", likes: nil, pet_id: 1},
  {title: "Sleep", description: "", likes: nil, pet_id: 1},
  {title: "profile", description: "", likes: nil, pet_id: 2},
  {title: "profile", description: "", likes: nil, pet_id: 3},
  {title: "profile", description: "", likes: nil, pet_id: 4},
  {title: "profile", description: "", likes: nil, pet_id: 5},
  {title: "profile", description: "", likes: nil, pet_id: 6},
  {title: "profile", description: "", likes: nil, pet_id: 7},
  {title: "profile", description: "", likes: nil, pet_id: 8},
  {title: "profile", description: "", likes: nil, pet_id: 9},
  {title: "profile", description: "", likes: nil, pet_id: 10},
  {title: "profile", description: "", likes: nil, pet_id: 11},
  {title: "profile", description: "", likes: nil, pet_id: 12},
  {title: "profile", description: "", likes: nil, pet_id: 13},
  {title: "profile", description: "", likes: nil, pet_id: 14},
  {title: "profile", description: "", likes: nil, pet_id: 15},
  {title: "profile", description: "", likes: nil, pet_id: 16},
  {title: "profile", description: "", likes: nil, pet_id: 17},
  {title: "profile", description: "", likes: nil, pet_id: 18},
  {title: "profile", description: "", likes: nil, pet_id: 19},
  {title: "profile", description: "", likes: nil, pet_id: 20},
  {title: "profile", description: "", likes: nil, pet_id: 21},
  {title: "profile", description: "", likes: nil, pet_id: 22},
  {title: "profile", description: "", likes: nil, pet_id: 23},
  {title: "profile", description: "", likes: nil, pet_id: 24},
  {title: "profile", description: "", likes: nil, pet_id: 25},
  {title: "profile", description: "", likes: nil, pet_id: 26},
  {title: "profile", description: "", likes: nil, pet_id: 27},
  {title: "profile", description: "", likes: nil, pet_id: 28},
  {title: "profile", description: "", likes: nil, pet_id: 29},
  {title: "profile", description: "", likes: nil, pet_id: 30},
  {title: "profile", description: "", likes: nil, pet_id: 31},
  {title: "profile", description: "", likes: nil, pet_id: 32},
  {title: "profile", description: "", likes: nil, pet_id: 33},
  {title: "profile", description: "", likes: nil, pet_id: 34},
  {title: "profile", description: "", likes: nil, pet_id: 35},
  {title: "profile", description: "", likes: nil, pet_id: 36},
  {title: "profile", description: "", likes: nil, pet_id: 37},
  {title: "profile", description: "", likes: nil, pet_id: 39}
])
Photo.create!([
  {description: "arm rest", likes: nil, album_id: 2, avatar: "WP_20160623_22_43_43_Pro.jpg"},
  {description: "hugs", likes: nil, album_id: 2, avatar: "WP_20160716_14_55_08_Pro.jpg"},
  {description: "profile", likes: nil, album_id: 3, avatar: "WP_20160602_12_30_55_Pro.jpg"},
  {description: "profile", likes: nil, album_id: 4, avatar: "37974-Tabby-cat-portrait-white-background.jpg"},
  {description: "profile", likes: nil, album_id: 5, avatar: "4927528676_87eeaeb293_o.jpg"},
  {description: "profile", likes: nil, album_id: 6, avatar: "cat-portraits3.jpeg"},
  {description: "profile", likes: nil, album_id: 7, avatar: "13704302_1563307740644877_1891684852_n.jpg"},
  {description: "profile", likes: nil, album_id: 8, avatar: "11931031_525785390907953_2058408278_a.jpg"},
  {description: "profile", likes: nil, album_id: 9, avatar: "13774757_1656410354579483_108987708_n.jpg"},
  {description: "profile", likes: nil, album_id: 10, avatar: "Siberian-Husky-dogs-13788924-1024-768.jpg"},
  {description: "profile", likes: nil, album_id: 11, avatar: "tibetan_mastiff_3.jpg"},
  {description: "profile", likes: nil, album_id: 12, avatar: "Bernese_Mountain_breed.jpg"},
  {description: "profile", likes: nil, album_id: 13, avatar: "maxresdefault.jpg"},
  {description: "profile", likes: nil, album_id: 14, avatar: "cats-cole-and-marmalade-explain.jpg"},
  {description: "profile", likes: nil, album_id: 15, avatar: "Alaskan_Malamute_Dog_2.jpg"},
  {description: "profile", likes: nil, album_id: 16, avatar: "polar-bear-in-pool_1935314i.jpg"},
  {description: "profile", likes: nil, album_id: 17, avatar: "1398474767000-pet-raccoon.jpg"},
  {description: "profile", likes: nil, album_id: 18, avatar: "Animals_Dogs_German_Shepherd_on_the_shore_025466_.jpg"},
  {description: "profile", likes: nil, album_id: 19, avatar: "Chihuahua-4.jpg"},
  {description: "profile", likes: nil, album_id: 20, avatar: "Hamster3.jpg"},
  {description: "profile", likes: nil, album_id: 21, avatar: "c0661a1f13eeffdf821d68798d89c5a8.jpg"},
  {description: "profile", likes: nil, album_id: 22, avatar: "a0a55f7dcf68c4080249cf71f88f65c4.jpg"},
  {description: "profile", likes: nil, album_id: 23, avatar: "NUyttbn.gif"},
  {description: "profile", likes: nil, album_id: 23, avatar: "funnypicture-heavy-breathing-cat.jpg"},
  {description: "profile", likes: nil, album_id: 24, avatar: "54270191958_ac3322f71dc8250e0601_512.png"},
  {description: "profile", likes: nil, album_id: 25, avatar: "IMG_4308.JPG"},
  {description: "profile", likes: nil, album_id: 26, avatar: "mtbl1cr.jpg"},
  {description: "profile", likes: nil, album_id: 27, avatar: "pM2DvuM.jpg"},
  {description: "profile", likes: nil, album_id: 28, avatar: "ekduGmd.jpg"},
  {description: "profile", likes: nil, album_id: 29, avatar: "M5zcPuk.jpg"},
  {description: "profile", likes: nil, album_id: 30, avatar: "swDXY2v.jpg"},
  {description: "profile", likes: nil, album_id: 31, avatar: "L9ZftiD.jpg"},
  {description: "profile", likes: nil, album_id: 32, avatar: "w2tuouc.jpg"},
  {description: "profile", likes: nil, album_id: 33, avatar: "xW2K0rt.jpg"},
  {description: "profile", likes: nil, album_id: 34, avatar: "zXWbLuW.jpg"},
  {description: "profile", likes: nil, album_id: 35, avatar: "zXWbLuW.jpg"},
  {description: "profile", likes: nil, album_id: 36, avatar: "7Vf94Tu.jpg"},
  {description: "profile", likes: nil, album_id: 37, avatar: "ntwBDRI.gif"},
  {description: "profile", likes: nil, album_id: 38, avatar: "Dog-GIFs-of-All-Time-27.gif"},
  {description: "profile", likes: nil, album_id: 40, avatar: "Funny-Dog-GIF.gif"},
  {description: "profile", likes: nil, album_id: 41, avatar: "oie_5181838bU3HJXJp.gif"},
  {description: "Profile", likes: nil, album_id: 1, avatar: "WP_20160713_20_22_04_Pro.jpg"}
])
